### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by bulkmoerls** [celisej567/Fake-CSM-Source-2013#11]
Im following the Level Pro And got stuck by the Creategameprojects.bat and said that i dont have the regkey vcproj and vcxproj. i looked everywhere but no luck. i almost given up hope with it and wanted the already compiled version of fake csm. if not, then is there anything i can do to fix this?
I only had Visual Studio 2022, and WANTED ME to use vs2013? I can't download it because i need a subscription for this. if you can help, then show me how can i fix this. if you cant, I'm About to give up hope for this.

**Comment by celisej567** [comment]
you need to read and do what `Level Newbie` says, and only then you need to do what `Level Pro`

**Comment by celisej567** [comment]
just find some torrent or something what will have vs2013 installer

**Comment by bulkmoerls** [comment]
okay i fixed it, but for some reason when i put 
```c++
$include csm.fgd
``` 

Launching Hammer, It Doesn't show up!
I tried putting CSM.fgd Into Hammer, but It Took memory!

**Comment by dgyClyde** [comment]
ok i found out how to fix it, locate and edit **csm.fgd**(with notepad or something)  just delete the first line where it says _"@include "halflife2.fgd"_, now it should be working in Hammer and the game
it's some kind of while(1) loop since you have requested **csm.fgd** at the end of **halflife2.fgd**

**Comment by celisej567** [comment]
ok great

**Comment by GuestSneezeOSDev** [comment]
> ok great

:trollface:
