### ISSUE TITLE
Source SDK 2013 Support

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [celisej567/Fake-CSM-Source-2013#13]
Blah blah add support for Source SDK

**Comment by celisej567** [comment]
K

**Comment by celisej567** [comment]
Anyway I was thinking to rewrite it entirely.

**Comment by GuestSneezeOSDev** [comment]
When would be the update?

**Comment by GuestSneezeOSDev** [comment]
could i implement this in my own engine based on source? https://github.com/Vortex-Engine/vortex-engine

**Comment by celisej567** [comment]
And of course manually increase projected texture limit

**Comment by GuestSneezeOSDev** [comment]
Thanks

**Comment by GuestSneezeOSDev** [comment]
make guide in wiki

**Comment by GuestSneezeOSDev** [comment]
when testing it gave me issues while compiling so this wont be resolved, I recommend using mapbase if you really want use it with Source SDK 2013 then have fun with a shitty experience
