### ISSUE TITLE
Cant find `$Include "$SRCDIR\game\server\server_mapbase.vpc"`

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [celisej567/Fake-CSM-Source-2013#14]
there is something wrong while following the wiki

**Comment by celisej567** [comment]
the point is to add the line itself somewhere in there.

**Comment by celisej567** [comment]
The `$Include "$SRCDIR\game\server\csm.vpc"` itself

**Comment by GuestSneezeOSDev** [comment]
which line do you recommend i add it in?

**Comment by celisej567** [comment]
anywhere where include stuff happens in server vpc

**Comment by GuestSneezeOSDev** [comment]
ok
