### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by valina354** [celisej567/Fake-CSM-Source-2013#2]
after compiling, ingame and trying to load map it says:
DataTable warning: No matching RecvTable for SendTable 'DT_EnvCascadeLight'.
DataTable warning: No matching RecvTable for SendTable 'DT_EnvCascadeLightSecond'.
DataTable warning: No matching RecvTable for SendTable 'DT_EnvCascadeLightThird'.
DataTable warning: No matching RecvTable for SendTable 'DT_LightOrigin'.
Client missing DT class CEnvCascadeLight
Client missing DT class CEnvCascadeLightSecond
Client missing DT class CEnvCascadeLightThird
Client missing DT class CLightOrigin
Host_EndGame: CL_ParseClassInfo_EndClasses: CreateDecoders failed.

**Comment by celisej567** [comment]
looks like you compiled only client or server

**Comment by valina354** [comment]
> looks like you compiled only client or server

i added $Include "csm.vpc" to server_base.vpc then compiled
