### ISSUE TITLE
CSM bleeds through walls.

### ISSUE THREAD

**Issue by valina354** [celisej567/Fake-CSM-Source-2013#3]
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/80889633/d8370f68-2c29-401b-a293-bfa1aa05e9de)
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/80889633/897c3e08-e47e-4e04-a57c-d88e64c2dacb)

**Comment by notfoundname** [comment]
It's hard to see anything on these screenshots.
It usually renders through because it is too thin or some sides are textures as "nodraw".

**Comment by celisej567** [comment]
how to fix: just make walls be not nodraw outside AND make 2 layers of walls that will not touch each other

**Comment by celisej567** [comment]
Or you can try to find some solution in mat_slopescale_depthbias and in some other mat_ console command

**Comment by celisej567** [comment]
Im just using `mat_slopescaledepthbias_shadowmap 4` , `mat_depthbias_shadowmap 0.00005` and `r_flashlightdepthres 4096` . this can fix some problems

**Comment by valina354** [comment]
> how to fix: just make walls be not nodraw outside or make 2 layers of walls that will not touch each other

**Comment by valina354** [comment]
actually im having the same issue again but on another map, for my mod, theres no nodraw textures and i think the walls are thick enough, this is the vmf: https://drive.google.com/file/d/1Y94vOLWhfExBELE-kxBrrxzjIhGpwJow/view?usp=sharing

**Comment by celisej567** [comment]
What about 2 layers of walls

**Comment by valina354** [comment]
> What about 2 layers of walls

adding 2 layer walls fixes it a bit at closer distance, but at further distance issue is again

**Comment by celisej567** [comment]
just make bigger distance between layers

**Comment by valina354** [comment]
still doesnt work, vmf is https://drive.google.com/file/d/1tTP9QaqMVMGxFsL3-bjJq6oI9jnTcrBQ/view?usp=drive_link

**Comment by celisej567** [comment]
Firstly, I dont have permission to use your URL. Second, if it doesnt work - you are doing something wrong.

**Comment by valina354** [comment]
> Firstly, I dont have permission to use your URL. Second, if it doesnt work - you are doing something wrong.

ok this should work https://www.mediafire.com/file/rv47d3m39ls1po4/proto_wasteland_02_smalltown_edit_01.vmf/file

**Comment by valina354** [comment]
oh i figured it out, i forgot to run the commands to make the csm look better im so dumb
