### ISSUE TITLE
i think this is an issue idk?!!

### ISSUE THREAD

**Issue by valina354** [celisej567/Fake-CSM-Source-2013#7]
are there any commands i can use to make csm look worse but improve fps? i tried lowering resolution but somehow that didnt fix it, im asking bcz fps reduces by 100 fps, from 130 fps to 30 fps

**Comment by valina354** [comment]
im using a gtx 1050 ti btw, a normal projected texture lowers fps by almost nothing, so how does this lower fps so so much?

**Comment by celisej567** [comment]
then i think you have to rewrite shader code entirely, because thats the main reason of low fps

**Comment by celisej567** [comment]
r_flashlightdepthres <resolution with power of 2>
try this
