### ISSUE TITLE
CSM overbright issue.

### ISSUE THREAD

**Issue by marcikaa78** [celisej567/Fake-CSM-Source-2013#8]
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/132925550/b47bffff-81dc-4ee1-bd27-a9319a5d89cd)
CSM still being overbright despite converting it to SDK_Shaders w/mapbase multitool.

pls help

Thank you

**Comment by celisej567** [comment]
some shaders that should be on displacements doesnt render flashlight same way as for brushes.
Convert your surface to displacement

**Comment by celisej567** [comment]
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/75926135/407ad8a9-1cae-489a-9271-7ed847d38fea)
ye im stupid and wrote it very shitty

**Comment by marcikaa78** [comment]
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/132925550/a9f32281-05f9-4521-8b13-83363f6718d9)
it is a displacement but its still overbright

**Comment by marcikaa78** [comment]
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/132925550/75f17bb8-4fe0-4f57-ac81-5b7b1b2a410d)

**Comment by celisej567** [comment]
why there is dev texture in hammer but in game you have grass

**Comment by marcikaa78** [comment]
changed it

**Comment by celisej567** [comment]
wait. i see you havent changed shader at this material. Mapbase uses different algoritm for flashlight filtering. Looks like you have to copy and change this exact material (or more if you need) from SDK folder to your mod

**Comment by marcikaa78** [comment]
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/132925550/8d987f0d-3954-4040-9674-0e47fc79d149)
this is the materials 

and this is the vmf: https://file.io/C9aZwV5AQm5m

**Comment by celisej567** [comment]
im talking about that grass

**Comment by marcikaa78** [comment]
in the meantime i "switched" to neotokyo assets and converted them, but im getting this now 
![image](https://github.com/celisej567/Fake-CSM-Source-2013/assets/132925550/bd110fb8-43bf-48c1-967d-595edac1941f)

**Comment by celisej567** [comment]
k I can't help you here.
